/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/blenderterrain.glb --transform 
Files: public/models/blenderterrain.glb [58.79MB] > C:\Users\tibog\Documents\VSCODE\wawa-game\blenderterrain-transformed.glb [2.16MB] (96%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/blenderterrain-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Plane.geometry} material={nodes.Plane.material} />
    </group>
  )
}

useGLTF.preload('/blenderterrain-transformed.glb')
