/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/grasssprite.glb --transform 
Files: public/models/grasssprite.glb [2.06MB] > C:\Users\tibog\Documents\VSCODE\wawa-game-2\grasssprite-transformed.glb [567.46KB] (72%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/grasssprite-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Grass_medium_3_GrassAtlas_0.geometry} material={materials.GrassAtlas} position={[1.25, 0, -0.625]} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/grasssprite-transformed.glb')
