/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/low_poly_flower.glb --transform 
Files: public/models/low_poly_flower.glb [75.97KB] > C:\Users\tibog\Documents\VSCODE\wawa-game-2\low_poly_flower-transformed.glb [9.8KB] (87%)
Author: beepbopghh (https://sketchfab.com/beepbopghh)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/low-poly-flower-e7553892ef3b4114bd0e510a6dc91d49
Title: Low Poly Flower
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/low_poly_flower-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.stem_0.geometry} material={materials.Material} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={0.463} />
    </group>
  )
}

useGLTF.preload('/low_poly_flower-transformed.glb')
