/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/myblenderterrain.glb --transform 
Files: public/models/myblenderterrain.glb [25.4MB] > C:\Users\tibog\Documents\VSCODE\wawa-game-2\myblenderterrain-transformed.glb [572KB] (98%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/myblenderterrain-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Plane.geometry} material={nodes.Plane.material} />
    </group>
  )
}

useGLTF.preload('/myblenderterrain-transformed.glb')
