/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/hyena_demo.glb --transform 
Files: public/models/hyena_demo.glb [7.48MB] > C:\Users\tibog\Documents\VSCODE\wawa-game\hyena_demo-transformed.glb [344.78KB] (95%)
Author: WildMesh 3D (https://sketchfab.com/WildMesh_3D)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/hyena-demo-free-download-c408114d705f4a77ad709b94b3abfe0f
Title: Hyena (Demo Free Download)
*/

import React from "react";
import { useGraph } from "@react-three/fiber";
import { useGLTF, useAnimations } from "@react-three/drei";
import { SkeletonUtils } from "three-stdlib";

export function Model(props) {
  const group = React.useRef();
  const { scene, animations } = useGLTF("/models/hyena_demo-transformed.glb");
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene]);
  const { nodes, materials } = useGraph(clone);
  const { actions } = useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <primitive object={nodes._rootJoint} />
        <skinnedMesh
          name="Object_88"
          geometry={nodes.Object_88.geometry}
          material={materials.Hyena}
          skeleton={nodes.Object_88.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/models/hyena_demo-transformed.glb");
