/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/quarry_rocks.glb --transform 
Files: public/models/quarry_rocks.glb [18.51MB] > C:\Users\tibog\Documents\VSCODE\wawa-game\quarry_rocks-transformed.glb [2.99MB] (84%)
Author: Studio Lab (https://sketchfab.com/studiolab.dev)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/quarry-rocks-e3649a3cfb1247afa8f097d3603f27fe
Title: Quarry Rocks
*/

import React, { useRef, useEffect } from "react";
import { useGLTF } from "@react-three/drei";
import { Group, Mesh } from "three";
import * as THREE from "three";

export const QuarryRocks = ({
  position = [0, 0, 0],
  scale = 1,
  rotation = [0, 0, 0],
  enabled = true,
  getTerrainHeight,
}) => {
  const groupRef = useRef(null);
  const { scene } = useGLTF("/models/quarry_rocks-transformed.glb");

  // Clone the scene to avoid modifying the original
  const clonedScene = scene.clone();

  // Apply shadows to all meshes in the scene
  useEffect(() => {
    if (clonedScene) {
      clonedScene.traverse((child) => {
        if (child instanceof Mesh) {
          child.castShadow = true;
          child.receiveShadow = true;

          // Ensure materials are properly configured
          if (child.material) {
            if (Array.isArray(child.material)) {
              child.material.forEach((material) => {
                if (material instanceof THREE.Material) {
                  material.needsUpdate = true;
                }
              });
            } else if (child.material instanceof THREE.Material) {
              child.material.needsUpdate = true;
            }
          }
        }
      });
    }
  }, [clonedScene]);

  // Calculate position with terrain height
  const finalPosition = [...position];
  const finalScale = Array.isArray(scale) ? scale : [scale, scale, scale];
  const finalRotation = rotation;

  // Calculate terrain height for Y position and adjust for model bottom
  useEffect(() => {
    if (getTerrainHeight && enabled && groupRef.current) {
      // Create a temporary group with scale applied to calculate bounds
      const tempScene = clonedScene.clone();
      const tempGroup = new THREE.Group();
      tempGroup.add(tempScene);
      tempGroup.scale.set(finalScale[0], finalScale[1], finalScale[2]);

      // Compute bounding box to find the bottom of the scaled model
      const bbox = new THREE.Box3();
      bbox.setFromObject(tempGroup);

      // Get the terrain height at this position
      const terrainY = getTerrainHeight(position[0], position[2]);

      // Offset by the model's bottom so it sits on terrain
      const bottomY = bbox.min.y;
      const adjustedY = terrainY - bottomY;

      groupRef.current.position.y = adjustedY;
      console.log(
        `QuarryRocks at [${position[0]}, ${
          position[2]
        }] -> terrain height: ${terrainY}, model bottom: ${bottomY.toFixed(
          2
        )}, adjusted Y: ${adjustedY.toFixed(2)}`
      );

      // Clean up temp group
      tempGroup.clear();
    }
  }, [position, getTerrainHeight, enabled, clonedScene, finalScale]);

  if (!enabled) {
    return null;
  }

  return (
    <group
      ref={groupRef}
      position={finalPosition}
      scale={finalScale}
      rotation={finalRotation}
    >
      <primitive object={clonedScene} />
    </group>
  );
};

// Also export the original Model function for backward compatibility
export function Model(props) {
  const { nodes, materials } = useGLTF("/models/quarry_rocks-transformed.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.QuarryRock01_QuarryRock01Shader_0.geometry}
        material={materials.QuarryRock01Shader}
        scale={0.01}
      />
      <mesh
        geometry={nodes.QuarryRock02_QuarryRock02Shader_0.geometry}
        material={materials.QuarryRock02Shader}
        position={[-5, 0, 0]}
        scale={0.01}
      />
      <mesh
        geometry={nodes.QuarryRock03_QuarryRock03Shader_0.geometry}
        material={materials.QuarryRock03Shader}
        position={[-11, -1.361, 0]}
        scale={0.01}
      />
      <mesh
        geometry={nodes.QuarryRock04_QuarryRock04Shader_0.geometry}
        material={materials.QuarryRock04Shader}
        position={[6, -1.232, 0]}
        scale={0.01}
      />
    </group>
  );
}

useGLTF.preload("/models/quarry_rocks-transformed.glb");
