/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/rock1.glb --transform 
Files: public/models/rock1.glb [3.84MB] > C:\Users\tibog\Documents\VSCODE\wawa-game\rock1-transformed.glb [622.47KB] (84%)
*/

import React, { useRef, useEffect, useMemo } from "react";
import { useGLTF } from "@react-three/drei";
import * as THREE from "three";

export function Rock1({
  position = [0, 0, 0],
  scale = 1,
  rotation = [0, 0, 0],
  enabled = true,
  getTerrainHeight,
  ...props
}) {
  const groupRef = useRef(null);
  const { scene } = useGLTF("/models/rock1-transformed.glb");

  // Clone the scene to avoid modifying the original
  const clonedScene = useMemo(() => scene.clone(), [scene]);

  // Apply shadows to all meshes in the scene and darken materials
  useEffect(() => {
    if (clonedScene) {
      clonedScene.traverse((child) => {
        if (child instanceof THREE.Mesh) {
          child.castShadow = true;
          child.receiveShadow = true;

          // Ensure materials are properly configured and darken them
          if (child.material) {
            if (Array.isArray(child.material)) {
              child.material.forEach((material) => {
                if (material instanceof THREE.Material) {
                  material.needsUpdate = true;
                  // Darken the material color
                  if (material.color) {
                    material.color.multiplyScalar(0.75); // Darken by 25%
                  }
                }
              });
            } else if (child.material instanceof THREE.Material) {
              child.material.needsUpdate = true;
              // Darken the material color
              if (child.material.color) {
                child.material.color.multiplyScalar(0.75); // Darken by 25%
              }
            }
          }
        }
      });
    }
  }, [clonedScene]);

  // Calculate position with terrain height
  const finalScale = Array.isArray(scale) ? scale : [scale, scale, scale];
  const finalRotation = rotation;

  // Calculate terrain height for Y position and adjust for model bottom
  useEffect(() => {
    if (enabled && groupRef.current) {
      if (getTerrainHeight) {
        // Create a temporary group with scale applied to calculate bounds
        const tempScene = clonedScene.clone();
        const tempGroup = new THREE.Group();
        tempGroup.add(tempScene);
        tempGroup.scale.set(finalScale[0], finalScale[1], finalScale[2]);

        // Compute bounding box to find the bottom of the scaled model
        const bbox = new THREE.Box3();
        bbox.setFromObject(tempGroup);

        // Get the terrain height at this position
        const terrainY = getTerrainHeight(position[0], position[2]);

        // Offset by the model's bottom so it sits on terrain
        const bottomY = bbox.min.y;
        // Use position[1] (Y value) as an offset - negative values sink deeper into ground
        const adjustedY = terrainY - bottomY + position[1];

        groupRef.current.position.y = adjustedY;
        console.log(
          `Rock1 at [${position[0]}, ${
            position[2]
          }] -> terrain height: ${terrainY}, model bottom: ${bottomY.toFixed(
            2
          )}, Y offset: ${position[1]}, final Y: ${adjustedY.toFixed(2)}`
        );

        // Clean up temp group
        tempGroup.clear();
      } else {
        // If no terrain height function, just use the Y position directly
        groupRef.current.position.y = position[1];
      }
    }
  }, [position, getTerrainHeight, enabled, clonedScene, finalScale]);

  if (!enabled) {
    return null;
  }

  return (
    <group
      ref={groupRef}
      position={position}
      scale={finalScale}
      rotation={finalRotation}
      {...props}
    >
      <primitive object={clonedScene} />
    </group>
  );
}

// Also export the original Model function for backward compatibility
export function Model(props) {
  const { nodes, materials } = useGLTF("/models/rock1-transformed.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.QuarryRock04_QuarryRock04Shader_0.geometry}
        material={materials.QuarryRock04Shader}
      />
    </group>
  );
}

useGLTF.preload("/models/rock1-transformed.glb");
