/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/simpleterrainblender.glb --transform 
Files: public/models/simpleterrainblender.glb [48.35KB] > C:\Users\tibog\Documents\VSCODE\wawa-game\simpleterrainblender-transformed.glb [5.23KB] (89%)
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function Model(props) {
  const { nodes, materials } = useGLTF(
    "/models/simpleterrainblender-transformed.glb"
  );
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Plane.geometry}
        material={materials["Material.001"]}
      />
    </group>
  );
}

useGLTF.preload("/models/simpleterrainblender-transformed.glb");
