/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/the_woman_and_the_swan.glb -S -T -t 
Files: public/models/the_woman_and_the_swan.glb [4.34MB] > C:\Users\tibog\Documents\VSCODE\wawa-game-2\the_woman_and_the_swan-transformed.glb [559.42KB] (87%)
Author: Dystopia (https://sketchfab.com/Dystopia)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/the-woman-and-the-swan-e6a7d5330c7d45749b403252ca5af40e
Title: The woman and the swan
*/

import * as THREE from "three";
import React, { useRef, useEffect } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Object_2: THREE.Mesh;
  };
  materials: {
    mesh_Model_Sketchfab: THREE.MeshStandardMaterial;
  };
};

export function Model({
  castShadow,
  receiveShadow,
  scale = 1,
  position,
  ...props
}: React.ComponentProps<"group">) {
  const { nodes, materials } = useGLTF(
    "/models/the_woman_and_the_swan-transformed.glb"
  ) as unknown as GLTFResult;
  const groupRef = useRef<THREE.Group>(null);
  const meshRef = useRef<THREE.Mesh>(null);

  // Compute bounding box to position model on floor
  useEffect(() => {
    if (meshRef.current && groupRef.current) {
      // Create a temporary mesh with rotation applied to compute bounding box
      const tempGeometry = meshRef.current.geometry.clone();
      const tempMesh = new THREE.Mesh(tempGeometry);
      tempMesh.rotation.x = -Math.PI / 2;
      tempMesh.updateMatrixWorld(true);

      // Compute bounding box in world space
      const bbox = new THREE.Box3();
      bbox.setFromObject(tempMesh);

      // Get the bottom Y value (min Y after rotation)
      const bottomY = bbox.min.y;

      // Adjust group position so bottom sits at Y=0
      const currentPos = Array.isArray(position) ? position : [0, 0, 0];
      const adjustedY = -bottomY * (typeof scale === "number" ? scale : 1);
      const currentY = typeof currentPos[1] === "number" ? currentPos[1] : 0;

      if (groupRef.current) {
        groupRef.current.position.y = currentY + adjustedY;
      }

      // Clean up temp geometry
      tempGeometry.dispose();
    }
  }, [scale, position]);

  return (
    <group
      ref={groupRef}
      position={position}
      scale={scale}
      {...props}
      dispose={null}
    >
      <mesh
        ref={meshRef}
        geometry={nodes.Object_2.geometry}
        material={materials.mesh_Model_Sketchfab}
        rotation={[-Math.PI / 2, 0, 0]}
        castShadow={castShadow}
        receiveShadow={receiveShadow}
      />
    </group>
  );
}

useGLTF.preload("/models/the_woman_and_the_swan-transformed.glb");
