/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/tree_elm.glb --transform 
Files: public/models/tree_elm.glb [7.08MB] > C:\Users\tibog\Documents\VSCODE\wawa-game\tree_elm-transformed.glb [1.1MB] (84%)
Author: High Quality Work (https://sketchfab.com/Varleyhal)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/tree-elm-6282055c4c0b42feafd3b5ab4cd919e4
Title: Tree Elm
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/tree_elm-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.tree_bark_0.geometry} material={materials.bark} position={[0.005, -0.05, -0.002]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes['tree_bark_for_small_bottom_branch_(circle)_0'].geometry} material={materials.bark_for_small_bottom_branch_circle} position={[0.005, -0.05, -0.002]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Plane001_leaf_0.geometry} material={materials.leaf} position={[-0.397, 13.925, -2.287]} rotation={[-0.323, -1.138, -0.387]} scale={2} />
    </group>
  )
}

useGLTF.preload('/tree_elm-transformed.glb')
