/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/treebillboard.glb --transform 
Files: public/models/treebillboard.glb [839.18KB] > C:\Users\tibog\Documents\VSCODE\wawa-game\treebillboard-transformed.glb [208.41KB] (75%)
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function Model(props) {
  const { nodes, materials } = useGLTF("/models/treebillboard-transformed.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.pine1_pine2_0.geometry}
        material={materials.pine2}
        position={[-15.714, 17.381, -26.766]}
        scale={43.479}
      />
    </group>
  );
}

useGLTF.preload("/models/treebillboard-transformed.glb");
